volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  uptime-kuma:

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3005:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - "9095:9090"
    command: "--config.file=/etc/config/prometheus.yaml"
    volumes:
      - /etc/prometheus:/etc/config:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  uptime-kuma:
    image: "louislam/uptime-kuma:1"
    container_name: "uptime-kuma"
    ports:
      - "3001:3001"
    dns:
      - "172.17.0.1"
    volumes:
      - "uptime-kuma:/app/data"
    restart: "always"
