services:
  litestream:
    image: litestream/litestream
    container_name: litestream_replica
    volumes:
      - hackem-bot-db:/data
      - /etc/litestream.yml:/etc/litestream.yml
    restart: unless-stopped
    command: ["replicate"]

volumes:
  hackem-bot-db:
    external: true
