# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports = [
    # "${inputs.nixpkgs}/nixos/modules/installer/sd-card/sd-image.nix"
  ];

  powerManagement.cpuFreqGovernor = "powersave";

  services.journald.extraConfig = ''
    Storage=volatile
    RuntimeMaxUse=64M
  '';
  boot.initrd.checkJournalingFS = true;

  # Hardware config?
  # boot.loader.grub.enable = false;
  # boot.loader.generic-extlinux-compatible.enable = true;
  # boot.loader.raspberryPi = {
  #   enable = true;
  #   version = 3;
  #   uboot.enable = true;
  #   firmwareConfig = ''
  #     force_turbo=1
  #   '';
  # };

  # boot.tmp.useTmpfs = true;

  # fileSystems = {
  #   "/" = {
  #     device = "/dev/disk/by-label/NIXOS_SD";
  #     fsType = "ext4";
  #     options = [ "noatime" ];
  #   };
  # };


  # fileSystems."/var/log" = {
	# fsType = "tmpfs";
	# options = [ "size=200M" ];
  # };

  # boot.supportedFilesystems = lib.mkForce [ ];

}
